"""FastAPI service for packaging order anomaly detection."""

from datetime import date, datetime, timezone
from pathlib import Path
from typing import Self
from uuid import uuid4

import joblib
import pandas as pd
from fastapi import FastAPI
from pydantic import BaseModel, ConfigDict, Field, model_validator


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MODEL_PATH = PROJECT_ROOT / "artifacts" / "isolation_forest.joblib"

EXPECTED_QUANTITY_MAXIMUM = {
    "Corrugated Box": 1200,
    "Flexible Pouch": 3500,
    "Product Label": 5000,
    "Folding Carton": 1500,
}


class OrderInput(BaseModel):
    """Raw operational order accepted by the API."""

    model_config = ConfigDict(
        extra="ignore",
        str_strip_whitespace=True,
    )

    order_id: str = Field(min_length=1)
    order_date: date
    completed_date: date
    product_type: str = Field(min_length=1)
    ordered_quantity: int = Field(gt=0)
    produced_quantity: int = Field(gt=0)
    defect_count: int = Field(ge=0)
    unit_price: int = Field(ge=0)

    @model_validator(mode="after")
    def validate_operational_values(self) -> Self:
        """Validate relationships between order fields."""

        if self.completed_date < self.order_date:
            raise ValueError(
                "completed_date tidak boleh sebelum order_date"
            )

        if self.defect_count > self.produced_quantity:
            raise ValueError(
                "defect_count tidak boleh melebihi "
                "produced_quantity"
            )

        return self


class AnalyzeRequest(BaseModel):
    """Request body for a collection of completed orders."""

    model_config = ConfigDict(
        extra="ignore",
        str_strip_whitespace=True,
    )

    source: str = Field(
        default="unknown",
        min_length=1,
    )

    orders: list[OrderInput] = Field(
        min_length=1,
    )


def load_model_bundle() -> dict:
    """Load the trusted model artifact generated by train.py."""

    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Model tidak ditemukan: {MODEL_PATH}. "
            "Jalankan 'python analytics/train.py' terlebih dahulu."
        )

    bundle = joblib.load(MODEL_PATH)

    required_keys = {
        "pipeline",
        "model_features",
        "metadata",
    }

    missing_keys = required_keys - set(bundle)

    if missing_keys:
        missing_text = ", ".join(sorted(missing_keys))

        raise ValueError(
            f"Model artifact tidak valid. "
            f"Key tidak ditemukan: {missing_text}"
        )

    return bundle


MODEL_BUNDLE = load_model_bundle()
MODEL_PIPELINE = MODEL_BUNDLE["pipeline"]
MODEL_METADATA = MODEL_BUNDLE["metadata"]
MODEL_FEATURES = MODEL_BUNDLE["model_features"]


app = FastAPI(
    title="PackSight Mini Analytics API",
    description=(
        "API untuk mendeteksi anomali pada order produksi "
        "packaging menggunakan Isolation Forest."
    ),
    version="1.0.0",
)


def build_feature_dataframe(
    orders: list[OrderInput],
) -> pd.DataFrame:
    """Convert validated orders into model features."""

    records = [
        order.model_dump(mode="json")
        for order in orders
    ]

    dataframe = pd.DataFrame(records)

    dataframe["order_date"] = pd.to_datetime(
        dataframe["order_date"]
    )

    dataframe["completed_date"] = pd.to_datetime(
        dataframe["completed_date"]
    )

    dataframe["lead_time_days"] = (
        dataframe["completed_date"]
        - dataframe["order_date"]
    ).dt.days

    dataframe["defect_rate"] = (
        dataframe["defect_count"]
        / dataframe["produced_quantity"]
    )

    dataframe["order_value"] = (
        dataframe["ordered_quantity"]
        * dataframe["unit_price"]
    )

    return dataframe


def build_anomaly_reasons(
    row: pd.Series,
) -> list[str]:
    """Create human-readable rule-based explanations."""

    reasons = []

    defect_rate = float(row["defect_rate"])
    lead_time_days = int(row["lead_time_days"])
    ordered_quantity = int(row["ordered_quantity"])
    product_type = str(row["product_type"])

    if defect_rate >= 0.08:
        reasons.append(
            "Defect rate melebihi 8%"
        )

    if lead_time_days >= 12:
        reasons.append(
            "Lead time mencapai 12 hari atau lebih"
        )

    expected_maximum = EXPECTED_QUANTITY_MAXIMUM.get(
        product_type
    )

    if (
        expected_maximum is not None
        and ordered_quantity > expected_maximum
    ):
        reasons.append(
            "Quantity jauh di atas rentang umum "
            f"untuk {product_type}"
        )

    if not reasons:
        reasons.append(
            "Kombinasi quantity, harga, defect rate, "
            "lead time, dan order value berbeda dari "
            "pola historis"
        )

    return reasons


def build_recommendations(
    row: pd.Series,
) -> list[str]:
    """Create operational follow-up suggestions."""

    recommendations = []

    defect_rate = float(row["defect_rate"])
    lead_time_days = int(row["lead_time_days"])
    ordered_quantity = int(row["ordered_quantity"])
    product_type = str(row["product_type"])

    if defect_rate >= 0.08:
        recommendations.append(
            "Minta tim Quality Control memeriksa "
            "penyebab produk cacat."
        )

    if lead_time_days >= 12:
        recommendations.append(
            "Periksa antrean produksi, ketersediaan "
            "bahan baku, mesin, dan kemungkinan rework."
        )

    expected_maximum = EXPECTED_QUANTITY_MAXIMUM.get(
        product_type
    )

    if (
        expected_maximum is not None
        and ordered_quantity > expected_maximum
    ):
        recommendations.append(
            "Konfirmasi kembali quantity order dan "
            "kapasitas produksi."
        )

    if not recommendations:
        recommendations.append(
            "Lakukan pemeriksaan manual terhadap detail order."
        )

    return recommendations


@app.get("/")
def read_root() -> dict:
    """Return basic service information."""

    return {
        "service": "PackSight Mini Analytics API",
        "status": "running",
        "documentation": "/docs",
        "health": "/health",
        "analyze": "/analyze",
    }


@app.get("/health")
def health_check() -> dict:
    """Return API and model readiness information."""

    return {
        "status": "healthy",
        "model_loaded": True,
        "model_name": MODEL_METADATA["model_name"],
        "model_trained_at": MODEL_METADATA["trained_at"],
        "scikit_learn_version": (
            MODEL_METADATA["scikit_learn_version"]
        ),
    }


@app.post("/analyze")
def analyze_orders(
    request: AnalyzeRequest,
) -> dict:
    """Analyze completed packaging orders."""

    dataframe = build_feature_dataframe(
        request.orders
    )

    feature_dataframe = dataframe[MODEL_FEATURES]

    preprocessor = MODEL_PIPELINE.named_steps[
        "preprocessor"
    ]

    model = MODEL_PIPELINE.named_steps["model"]

    transformed_features = preprocessor.transform(
        feature_dataframe
    )

    raw_predictions = model.predict(
        transformed_features
    )

    decision_values = model.decision_function(
        transformed_features
    )

    anomaly_mask = raw_predictions == -1

    anomalies = []

    for row_position, is_anomaly in enumerate(
        anomaly_mask
    ):
        if not bool(is_anomaly):
            continue

        row = dataframe.iloc[row_position]

        anomaly_score = -float(
            decision_values[row_position]
        )

        anomalies.append(
            {
                "order_id": str(row["order_id"]),
                "product_type": str(
                    row["product_type"]
                ),
                "ordered_quantity": int(
                    row["ordered_quantity"]
                ),
                "produced_quantity": int(
                    row["produced_quantity"]
                ),
                "defect_count": int(
                    row["defect_count"]
                ),
                "defect_rate_pct": round(
                    float(row["defect_rate"]) * 100,
                    2,
                ),
                "lead_time_days": int(
                    row["lead_time_days"]
                ),
                "order_value": int(
                    row["order_value"]
                ),
                "anomaly_score": round(
                    anomaly_score,
                    4,
                ),
                "reasons": build_anomaly_reasons(row),
                "recommendations": (
                    build_recommendations(row)
                ),
            }
        )

    anomalies.sort(
        key=lambda item: item["anomaly_score"],
        reverse=True,
    )

    total_order_value = int(
        dataframe["order_value"].sum()
    )

    total_produced_quantity = int(
        dataframe["produced_quantity"].sum()
    )

    total_defect_count = int(
        dataframe["defect_count"].sum()
    )

    overall_defect_rate_pct = round(
        (
            total_defect_count
            / total_produced_quantity
            * 100
        ),
        2,
    )

    average_lead_time_days = round(
        float(dataframe["lead_time_days"].mean()),
        2,
    )

    anomaly_count = len(anomalies)

    return {
        "analysis_id": str(uuid4()),
        "analyzed_at": datetime.now(
            timezone.utc
        ).isoformat(),
        "source": request.source,
        "status": (
            "alert"
            if anomaly_count > 0
            else "normal"
        ),
        "model": {
            "name": MODEL_METADATA["model_name"],
            "trained_at": MODEL_METADATA["trained_at"],
        },
        "record_count": len(dataframe),
        "normal_count": (
            len(dataframe) - anomaly_count
        ),
        "anomaly_count": anomaly_count,
        "kpis": {
            "total_order_value": total_order_value,
            "total_produced_quantity": (
                total_produced_quantity
            ),
            "total_defect_count": total_defect_count,
            "overall_defect_rate_pct": (
                overall_defect_rate_pct
            ),
            "average_lead_time_days": (
                average_lead_time_days
            ),
        },
        "anomalies": anomalies,
    }